version: '3.9'

services:
  daosrv:
    container_name: dao_backend_server
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '${SERVER_PORT}:${SERVER_PORT}'
    networks:
      - net
    depends_on:
      - postgres
    restart: always

  postgres:
    container_name: ${POSTGRES_CONTAINER_NAME}
    image: postgres
    environment:
      PGDATA: /data/postgres
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - yar_dao_postgres_vol:/data/postgres
    ports:
      - '${POSTGRES_PORT_EXT}:5432'
    networks:
      - net
    restart: always

networks:
  net:
    name: ${APP_NETWORK}
    driver: bridge

volumes:
  yar_dao_postgres_vol: